config/routes.rb
Payroll::Engine.routes.draw do
  resources :employee, only: [:new, :create, :index] do
    resources :salary_infos, only: [:new, :create, :index]
    resources :incentives, only: [:new, :create, :index]
    resources :bonuses, only: [:new, :create, :index]
    resources :deductions, only: [:new, :create, :index]
    resources :leave_entries, only: [:new, :create, :index]
    resources :leave_settings, only: [:new, :create, :index]
    resources :payslips, only: :index
  end
  resources :leave_types, only: [:new, :create, :index]
end

app/models/payroll/application_record.rb
module Payroll
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/payroll/bonus.rb
module Payroll
  class Bonus < ApplicationRecord
    belongs_to :employee
  end
end

app/models/payroll/deduction.rb
module Payroll
  class Deduction < ApplicationRecord
    belongs_to :employee
  end
end

app/models/payroll/employee.rb
module Payroll
  class Employee < ApplicationRecord
    has_many :leave_entries
    has_many :salary_infos
    has_many :incentives
    has_many :deductions
    has_many :bonuses

    validates_presence_of :name

    enum gender: [:female, :male]
  end
end

app/models/payroll/incentive.rb
module Payroll
  class Incentive < ApplicationRecord
    belongs_to :employee
  end
end

app/models/payroll/leave_entry.rb
module Payroll
  class LeaveEntry < ApplicationRecord
    belongs_to :leave_type

    scope :absent, -> (emp_id) {
      obj = Payroll::LeaveType.where(title: 'absent').first
      where("employee_id=? and leave_type_id=?", emp_id, obj.id)
    }
    scope :sickness, -> (emp_id) {
      obj = Payroll::LeaveType.where(title: 'sickness').first
      where("employee_id=? and leave_type_id=?", emp_id, obj.id)
    }
    scope :break, -> (emp_id) {
      obj = Payroll::LeaveType.where(title: 'break').first
      where("employee_id=? and leave_type_id=?", emp_id, obj.id)
    }
    scope :casual, -> (emp_id) {
      obj = Payroll::LeaveType.where(title: 'casual').first
      where("employee_id=? and leave_type_id=?", emp_id, obj.id)
    }
  end
end

app/models/payroll/leave_setting.rb
module Payroll
  class LeaveSetting < ApplicationRecord
    belongs_to :leave_type
  end
end

app/models/payroll/leave_type.rb
module Payroll
  class LeaveType < ApplicationRecord
  end
end

app/models/payroll/salary_info.rb
module Payroll
  class SalaryInfo < ApplicationRecord
    validates_presence_of :employee_id, :salary_type, :salary_amount, :remarks
    belongs_to :employee
  end
end

app/controllers/payroll/application_controller.rb
module Payroll
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/payroll/bonuses_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class BonusesController < ApplicationController
    before_action :find_employee

    def index
      @bonuses = Payroll::Bonus.all
    end


    def new
      @bonus = Payroll::Bonus.new
    end

    def create
      @bonus = Payroll::Bonus.new(bonus_params.merge(employee_id: @employee.id))
      if @bonus.save
        redirect_to employee_bonuses_path(@employee)
      else
        render :new
      end
    end

    private

    def bonus_params
      params.require(:bonus).permit(:employee_id, :name, :amount, :remarks)
    end

    def find_employee
      @employee = Payroll::Employee.find(params[:employee_id])
    end
  end
end

app/controllers/payroll/deductions_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class DeductionsController < ApplicationController
    before_action :find_employee

    def index
      @deductions = Payroll::Deduction.all
    end

    def new
      @deduction = Payroll::Deduction.new
    end

    def create
      @deduction = Payroll::Deduction.new(deduction_params.merge(employee_id: @employee.id))
      if @deduction.save
        redirect_to employee_deductions_path(@employee)
      else
        render :new
      end
    end

    private

    def deduction_params
      params.require(:deduction).permit(:advance_pay, :professional_tax, :loan, :provisional_fund, :remarks)
    end

    def find_employee
      @employee = Payroll::Employee.find(params[:employee_id])
    end
  end
end

app/controllers/payroll/employee_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class EmployeeController < ApplicationController
    def index
      @employee = Payroll::Employee.all
    end

    def new
      @employee = Payroll::Employee.new
    end

    def create
      @employee = Payroll::Employee.new(employee_params)
      if @employee.save
        redirect_to employee_index_path
      else
        render :new
      end
    end

    private

    def employee_params
      params.require(:employee).permit(:name, :father, :gender, :date_of_birth, :address, :city, :state, :pincode, :contact_no, :designation, :department, :date_of_joining, :photo, :remarks)
    end
  end
end

app/controllers/payroll/incentives_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class IncentivesController < ApplicationController
    before_action :find_employee

    def index
      @incentives = Payroll::Incentive.all
    end

    def new
      @incentive = Payroll::Incentive.new
    end

    def create
      @incentive = Payroll::Incentive.new(incentive_params.merge(employee_id: @employee.id))
      if @incentive.save
        redirect_to employee_incentives_path(@employee)
      else
        render :new
      end
    end

    private

    def incentive_params
      params.require(:incentive).permit(:hra, :da, :ta, :medical, :remarks)
    end

    def find_employee
      @employee = Payroll::Employee.find(params[:employee_id])
    end
  end
end

app/controllers/payroll/leave_entries_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class LeaveEntriesController < ApplicationController
    before_action :find_employee

    def index
      @leave_entries = Payroll::LeaveEntry.all
    end

    def new
      @leave_entry = Payroll::LeaveEntry.new
    end

    def create
      @leave_entry = Payroll::LeaveEntry.new(leave_entry_params.merge(employee_id: @employee.id))
      if @leave_entry.save
        redirect_to employee_leave_entries_path(@employee)
      else
        render :new
      end
    end

    private

    def leave_entry_params
      params.require(:leave_entry).permit(:leave_type_id, :total_leave, :leave_from, :leave_to, :balance_leave)
    end

    def find_employee
      @employee = Payroll::Employee.find(params[:employee_id])
    end
  end
end

app/controllers/payroll/leave_settings_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class LeaveSettingsController < ApplicationController
    before_action :find_employee

    def index
      @leave_settings = Payroll::LeaveSetting.all
    end

    def new
      @leave_setting = Payroll::LeaveSetting.new
    end

    def create
      @leave_setting = Payroll::LeaveSetting.new(leave_setting_params.merge(employee_id: @employee.id))
      if @leave_setting.save
        redirect_to employee_leave_settings_path(@employee.id)
      else
        render :new
      end
    end

    private

    def leave_setting_params
      params.require(:leave_setting).permit(:leave_type_id, :jan, :feb, :mar, :apr, :may, :jun, :jul, :aug, :sep, :oct, :nov, :dec)
    end

    def find_employee
      @employee = Payroll::Employee.find(params[:employee_id])
    end
  end
end

app/controllers/payroll/leave_types_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class LeaveTypesController < ApplicationController
    def index
      @leave_types = Payroll::LeaveType.all
    end

    def new
      @leave_type = Payroll::LeaveType.new
    end

    def create
      @leave_type = Payroll::LeaveType.new(leave_type_params)
      if @leave_type.save
        redirect_to leave_types_path
      else
        render :new
      end
    end

    private

    def leave_type_params
      params.require(:leave_type).permit(:title)
    end
  end
end

app/controllers/payroll/payslips_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class PayslipsController < ApplicationController
    def index
      @employee = Payroll::Employee.find(params[:employee_id])
      @incentive = @employee.incentives.last
      @deduction = @employee.deductions.last
    end
  end
end

app/controllers/payroll/salary_infos_controller.rb
require_dependency "payroll/application_controller"

module Payroll
  class SalaryInfosController < ApplicationController
    before_action :find_employee

    def index
      @salary_infos = Payroll::SalaryInfo.all
    end

    def new
      @salary_info = Payroll::SalaryInfo.new
    end

    def create
      @salary_info = Payroll::SalaryInfo.new(salary_info_params.merge(employee_id: @employee.id))
      if @salary_info.save
        redirect_to employee_salary_infos_path(@employee)
      else
        render :new
      end
    end

    private

    def salary_info_params
      params.require(:salary_info).permit(:salary_type, :salary_amount, :remarks)
    end

    def find_employee
      @employee = Payroll::Employee.find(params[:employee_id])
    end
  end
end

app/helpers/payroll/application_helper.rb
module Payroll
  module ApplicationHelper
  end
end

app/views/payroll/employee/_form.html.erb
<%= simple_form_for @employee, url: employee_index_path, method: :post do |form| %>
<div class="form-group">
  <%= form.input :name %>
</div>
<div class="form-group">
  <%= form.input :father %>
</div>
<div class="form-group">
  <%= form.input :gender, as: :select, collection: Payroll::Employee.genders.map {|x,y| [x, x]}, prompt: 'Select gender' %>
</div>
<div class="form-group">
  <%= form.input :date_of_birth %>
</div>
<div class="form-group">
  <%= form.input :address %>
</div>
<div class="form-group">
  <%= form.input :city %>
</div>
<div class="form-group">
  <%= form.input :state %>
</div>
<div class="form-group">
  <%= form.input :pincode %>
</div>
<div class="form-group">
  <%= form.input :contact_no %>
</div>
<div class="form-group">
  <%= form.input :designation %>
</div>
<div class="form-group">
  <%= form.input :department %>
</div>
<div class="form-group">
  <%= form.input :date_of_joining %>
</div>
<div class="form-group">
  <%= form.input :remarks %>
</div>
<div class="actions">
  <%= form.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/payroll/employee/_index.html.erb
<p><%= link_to 'Add New', new_employee_path %></p>
<div class="table table-responsive">
  <table class="table table-hover table-stripped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Father</th>
        <th>Gender</th>
        <th>Date of Birth</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Pincode</th>
        <th>Contact No</th>
        <th>Designation</th>
        <th>Department</th>
        <th>Date of Joining</th>
        <!--<th>Photo</th>-->
        <th>Remarks</th>
        <th>Total Absent</th>
        <th>Total Sickness</th>
        <th>Total Break</th>
        <th>Total Casual</th>
      </tr>
    </thead>

    <tbody>
      <% @employee.each do |emp| %>
        <tr>
          <td><%= emp.name %></td>
          <td><%= emp.father %></td>
          <td><%= emp.gender %></td>
          <td><%= emp.date_of_birth %></td>
          <td><%= emp.address %></td>
          <td><%= emp.city %></td>
          <td><%= emp.state %></td>
          <td><%= emp.pincode %></td>
          <td><%= emp.contact_no %></td>
          <td><%= emp.designation %></td>
          <td><%= emp.department %></td>
          <td><%= emp.date_of_joining %></td>
          <td><%= emp.remarks %></td>
          <td><%= Payroll::LeaveEntry.absent(emp.id).count %></td>
          <td><%= Payroll::LeaveEntry.sickness(emp.id).count %></td>
          <td><%= Payroll::LeaveEntry.break(emp.id).count %></td>
          <td><%= Payroll::LeaveEntry.casual(emp.id).count %></td>
          <td><%= link_to 'Basic Salary', employee_salary_infos_path(emp.id) %></td>
          <td><%= link_to 'Incentives', employee_incentives_path(emp.id) %></td>
          <td><%= link_to 'Bonuses', employee_bonuses_path(emp.id) %></td>
          <td><%= link_to 'Deductions', employee_deductions_path(emp.id) %></td>
          <td><%= link_to 'Leave Settings', employee_leave_settings_path(emp.id) %></td>
          <td><%= link_to 'Leave Entries', employee_leave_entries_path(emp.id) %></td>
          <td><%= link_to 'Pay Slips', employee_payslips_path(emp.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/payroll/employee/index.html.erb
<div class="card">
  <div class="card-header">
    <div class="row">
      <div class="col-sm-6">
        <strong class="card-title">Users</strong>
      </div>
    </div>
  </div>
  <div class="card-body">
    <%= render 'index' %>
  </div>
</div>

app/views/payroll/employee/new.html.erb
<div class="card">
  <div class="card-header">
    <h4 class="card-title">New Department</h4>
  </div>
  <div class="card-body">
    <%= render 'form', department: @department %>
  </div>
</div>

<%= link_to 'Back', "#" %>